### ISSUE TITLE
Bridge plot where age1 index is added fails because the models have different numbers of indices

### ISSUE THREAD

**Issue by cgrandin** [pacific-hake/hake-assessment#877]
This code fails (only for bridge models group 2:

https://github.com/pacific-hake/hake-assessment/blob/f26c5763351f07c5ddd58635a94d28d615145076/doc/main-figures/main-figures.rnw#L414

**Comment by cgrandin** [comment]
Do this after switching to MCMC. The problem may go away on its own

**Comment by andrew-edwards** [comment]
Didn't go away on it's own with MCMC. See #880 as we may not include it.

**Comment by aaronmberger-nwfsc** [comment]
We may have to fill in the indexfleets function variable; SSplotComparisons says:
indexfleets:
Vector of fleet numbers for each model for which to compare indices of abundance. Only necessary if any model has more than one index.

so maybe something like indexfleets = c(2,2,c(2:3),2)   if model 1, 2, and 4 have one index listed as fleet two (like ours without age one index; and model 3 has fleet 2 index (acoustic survey) and fleet 3 index (age-1 survey).  Or something like that - I can never remember so have to do trial and error.

**Comment by aaronmberger-nwfsc** [comment]
actually it is just adding:
indexfleets=c(2,2,2,2) or indexfleets=c(3,3,3,3)
if you want age 2+ index shown (fleet 2) or age 1 index shown (fleet 3) for a 4 model comparison

I'll fix now unless someone already has

**Comment by aaronmberger-nwfsc** [comment]
looks like this has been fixed already so closing

**Comment by andrew-edwards** [comment]
It's not completely fixed, as last year we had a bottom right panel showing age-1 index, but currently just have:
![image](https://user-images.githubusercontent.com/6977190/150615777-ea83fe77-97e6-4ca9-b063-3f8a4b1f25ee.png)

But I think we're fine just keeping it as we are for now, given constraints. Then can also close #880.

**Comment by cgrandin** [comment]
I see this is closed but not sure it should be so I will re-open.

Did we agree that we don't need the index fit plot for bridging? I though @kellijohnson-NOAA suggested we should show it since we are adding the age -1 index as one of the bridging steps and we want to see if that affects the age 2+ index fit (bottom right panel).

**Comment by aaronmberger-nwfsc** [comment]
I think you are right.  Our first bridging sequence can show the acoustic survey index in layout position 5, and then perhaps our second bridging sequence (that has the age one survey added) could have the acoustic survey index fit in layout position 4 and the age-1 index fit in position 5.  This can be done after we rebuild the rds file.

**Comment by andrew-edwards** [comment]
This breaks `fig:main-index-base-alternative-4` now. Not sure why but it's the same function that Chris fixed (or not, ha ha !) in the above commit....
```
make.comparison.plot(c(list(base.model), sens.models.4),
+                      subplots = 14,
+                      model.names = c(base.model.name, sens.model.names.4),
+                      legend = TRUE,
+                      end.yr = end.yr)
> 
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(indices$year) : no non-missing arguments to min; returning Inf
2: In max(indices$year) : no non-missing arguments to max; returning -Inf
> 
```

**Comment by andrew-edwards** [comment]
Also
```
fig:main-biomass-recruitment-retrospective
fig:retrospective-biomass-base-age1   (age-1 appendix)
```
I'd guess it's the same fix for all. And easier for you to do ;)

**Comment by andrew-edwards** [comment]
Relatedly I'm just removing plots of sens.model.names.5  because it's just a dummy one that we didn't need. Currently
